### ISSUE TITLE
[Question] - Do we need cipher?

### ISSUE THREAD

**Issue by GuilhE** [Fi5t/authenticate-me#3]
Hello,

First of all, awesome article and even awesome repo. Just a quick question:
Since nowadays we have `EncryptedSharedPreferences` do we really need to use `Pbkdf2Factory` and all that logic of coding and decoding to safely store the pin? In your sample you end up using `EncryptedSharedPreferences`but you use another security layer on top of it. Is it just another security layer or it has other purposes?

Thanks.

**Comment by Fi5t** [comment]
Hello @GuilhE! Thank you for the good appreciation of my work. 
I'm using `EncryptedSharedPreferences` as some "base security layer" for an application. Things like `PBKDF2` are using for additional security mechanisms.

Things like `PBKDF2` are used for additional security mechanisms. For instance, if you don't want to store a PIN, you got to use Tink + PBKDF2 in such a way as I showed in my article.

And you need to use `Cipher` if you want to achieve an additional layer of encryption with biometrics. This approach is described in the article too. Of course, you can split these mechanisms and don't use biometrics for encryption operations. It's completely up to you.
